// trips.js — Kiespret dataset v1
// Scope: uitsluitend zonvakanties voor Nederlandse koppels 28–45
// Sfeer-tags: 'strand' | 'actief' | 'resort'
// Prijs: indicatief per persoon o.b.v. april 2026, vliegveld AMS tenzij anders

const trips = [

  // ── MALLORCA ─────────────────────────────────────────────────────────────
  {
    id: 'mallorca-adults-resort',
    title: 'Adults only resort Mallorca',
    destination: 'Mallorca, Spanje',
    hotelName: 'Cala Breeze Resort',
    sfeer: ['resort', 'comfort', 'allinclusive'],
    aanbieder: 'TUI',
    boardType: 'All-inclusive',
    vluchtduur: '2u15',
    adultsOnly: true,
    audience: 'couples',
    matchReason: 'Ideaal voor koppels die willen ontzorgen',
    whyThisTrip: 'All-inclusive resort op loopafstand van het strand — geen keuzes, alleen genieten',
    tags: ['adults-only', 'strand', 'pool', 'allinclusive', 'resort'],
    highlights: ['Infinity pool', 'Inclusief drankjes & maaltijden', '150m van strand'],
    description: 'Mallorca combineert zeker weer, turquoise water en uitstekende service. Dit adults-only resort is perfect voor een koppel dat écht wil ontspannen.',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    affiliatePartner: 'TUI',
    variants: [
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 699,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/mallorca/' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 899,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/mallorca/' },
      { maand: 'juli',     duur: 7,  airport: 'AMS', prijs: 1099, affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/mallorca/' },
      { maand: 'augustus', duur: 7,  airport: 'AMS', prijs: 1199, affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/mallorca/' },
      { maand: 'september',duur: 7,  airport: 'AMS', prijs: 849,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/mallorca/' },
      { maand: 'mei',      duur: 14, airport: 'AMS', prijs: 1199, affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/mallorca/' },
      { maand: 'juni',     duur: 14, airport: 'AMS', prijs: 1499, affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/mallorca/' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  {
    id: 'mallorca-strand-actief',
    title: 'Actieve strandweek Mallorca',
    destination: 'Mallorca, Spanje',
    hotelName: 'Porto Playa Hotel',
    sfeer: ['actief', 'strand', 'natuur'],
    aanbieder: 'Sunweb',
    boardType: 'Halfpension',
    vluchtduur: '2u15',
    adultsOnly: false,
    audience: 'couples',
    matchReason: 'Strand én avontuur in één week',
    whyThisTrip: 'Overdag wandelen of snorkelen, \'s avonds genieten van Mallorca\'s beste restaurants',
    tags: ['strand', 'actief', 'snorkelen', 'wandelen', 'halfpension'],
    highlights: ['Huurfiets of -scooter mogelijk', 'Snorkelspot op 10 min', 'Basis aan het strand'],
    description: 'Voor koppels die niet stilzitten. Mallorca heeft schitterende kustpaden, verborgen baaien en gezellige dorpen. Overdag actief, \'s avonds relaxed.',
    imageUrl: 'https://images.unsplash.com/photo-1571406252241-db0280bd36cd?w=800&q=80',
    affiliatePartner: 'Sunweb',
    variants: [
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 649,  affiliateUrl: 'https://www.sunweb.nl/vakantie/spanje/mallorca' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 799,  affiliateUrl: 'https://www.sunweb.nl/vakantie/spanje/mallorca' },
      { maand: 'juli',     duur: 7,  airport: 'AMS', prijs: 999,  affiliateUrl: 'https://www.sunweb.nl/vakantie/spanje/mallorca' },
      { maand: 'augustus', duur: 7,  airport: 'AMS', prijs: 1099, affiliateUrl: 'https://www.sunweb.nl/vakantie/spanje/mallorca' },
      { maand: 'september',duur: 7,  airport: 'AMS', prijs: 749,  affiliateUrl: 'https://www.sunweb.nl/vakantie/spanje/mallorca' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── GRAN CANARIA ─────────────────────────────────────────────────────────
  {
    id: 'gran-canaria-resort',
    title: 'All-inclusive resort Gran Canaria',
    destination: 'Gran Canaria, Spanje',
    hotelName: 'Playa del Inglés Resort',
    sfeer: ['resort', 'comfort', 'allinclusive'],
    aanbieder: 'Corendon',
    boardType: 'All-inclusive',
    vluchtduur: '4u',
    adultsOnly: false,
    audience: 'couples',
    matchReason: 'Zon gegarandeerd, ook in de winter',
    whyThisTrip: 'Gran Canaria heeft het hele jaar door 24 graden. All-inclusive resort aan de duinen van Maspalomas.',
    tags: ['strand', 'pool', 'allinclusive', 'resort', 'zeker-weer'],
    highlights: ['Jaar-rond zeker zon', 'Duinen van Maspalomas op 5 min', 'Groot zwembadcomplex'],
    description: 'Geen gok op het weer — Gran Canaria heeft 300 dagen zon per jaar. Ideaal voor een ontspannen all-inclusive week waarbij je echt niks hoeft te regelen.',
    imageUrl: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800&q=80',
    affiliatePartner: 'Corendon',
    variants: [
      { maand: 'januari',  duur: 7,  airport: 'AMS', prijs: 849,  affiliateUrl: 'https://www.corendon.nl/vakantie/gran-canaria' },
      { maand: 'februari', duur: 7,  airport: 'AMS', prijs: 849,  affiliateUrl: 'https://www.corendon.nl/vakantie/gran-canaria' },
      { maand: 'maart',    duur: 7,  airport: 'AMS', prijs: 799,  affiliateUrl: 'https://www.corendon.nl/vakantie/gran-canaria' },
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 749,  affiliateUrl: 'https://www.corendon.nl/vakantie/gran-canaria' },
      { maand: 'oktober',  duur: 7,  airport: 'AMS', prijs: 799,  affiliateUrl: 'https://www.corendon.nl/vakantie/gran-canaria' },
      { maand: 'november', duur: 7,  airport: 'AMS', prijs: 849,  affiliateUrl: 'https://www.corendon.nl/vakantie/gran-canaria' },
      { maand: 'december', duur: 7,  airport: 'AMS', prijs: 999,  affiliateUrl: 'https://www.corendon.nl/vakantie/gran-canaria' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── TENERIFE ─────────────────────────────────────────────────────────────
  {
    id: 'tenerife-actief',
    title: 'Actief op Tenerife',
    destination: 'Tenerife, Spanje',
    hotelName: 'Los Gigantes Boutique',
    sfeer: ['actief', 'natuur', 'strand'],
    aanbieder: 'TUI',
    boardType: 'Ontbijt',
    vluchtduur: '4u15',
    adultsOnly: false,
    audience: 'couples',
    matchReason: 'Natuur, vulkaan en zee in één',
    whyThisTrip: 'Wandel naar de top van de Teide (3.715m) en eindig de dag aan het zwarte strand.',
    tags: ['actief', 'wandelen', 'natuur', 'vulkaan', 'strand'],
    highlights: ['Teide nationaalpark op 1u rijden', 'Snorkelen bij Los Gigantes', 'Zwarte lavastranden'],
    description: 'Tenerife is meer dan zon en strand. De vulkaan Teide, groen noorden en dramatische kliffen — perfect voor koppels die avontuur zoeken.',
    imageUrl: 'https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=800&q=80',
    affiliatePartner: 'TUI',
    variants: [
      { maand: 'maart',    duur: 7,  airport: 'AMS', prijs: 699,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/tenerife/' },
      { maand: 'april',    duur: 7,  airport: 'AMS', prijs: 749,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/tenerife/' },
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 749,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/tenerife/' },
      { maand: 'oktober',  duur: 7,  airport: 'AMS', prijs: 799,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/tenerife/' },
      { maand: 'november', duur: 7,  airport: 'AMS', prijs: 749,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/tenerife/' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── KRETA ────────────────────────────────────────────────────────────────
  {
    id: 'kreta-strand-relax',
    title: 'Ontspannen strandweek Kreta',
    destination: 'Kreta, Griekenland',
    hotelName: 'Elounda Beach Club',
    sfeer: ['strand', 'rustig', 'zon'],
    aanbieder: 'Sunweb',
    boardType: 'Halfpension',
    vluchtduur: '3u30',
    adultsOnly: false,
    audience: 'couples',
    matchReason: 'Blauwste water van de Middellandse Zee',
    whyThisTrip: 'Kreta heeft het helderste water van Griekenland, heerlijk eten en een relaxte sfeer.',
    tags: ['strand', 'rustig', 'zon', 'eten', 'halfpension'],
    highlights: ['Helder turquoise water', 'Grieks eten op loopafstand', 'Rustige baai'],
    description: 'Kreta is groot, mooi en relaxed. Geen massatoerisme maar authentieke Griekse sfeer, perfect voor koppels die willen opladen.',
    imageUrl: 'https://images.unsplash.com/photo-1533104816931-20fa691ff6ca?w=800&q=80',
    affiliatePartner: 'Sunweb',
    variants: [
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 699,  affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/kreta' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 849,  affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/kreta' },
      { maand: 'juli',     duur: 7,  airport: 'AMS', prijs: 1049, affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/kreta' },
      { maand: 'augustus', duur: 7,  airport: 'AMS', prijs: 1149, affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/kreta' },
      { maand: 'september',duur: 7,  airport: 'AMS', prijs: 849,  affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/kreta' },
      { maand: 'oktober',  duur: 7,  airport: 'AMS', prijs: 699,  affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/kreta' },
      { maand: 'mei',      duur: 10, airport: 'AMS', prijs: 949,  affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/kreta' },
      { maand: 'juni',     duur: 10, airport: 'AMS', prijs: 1099, affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/kreta' },
      { maand: 'september',duur: 10, airport: 'AMS', prijs: 1099, affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/kreta' },
      { maand: 'mei',      duur: 14, airport: 'AMS', prijs: 1199, affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/kreta' },
      { maand: 'juni',     duur: 14, airport: 'AMS', prijs: 1399, affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/kreta' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── RHODOS ───────────────────────────────────────────────────────────────
  {
    id: 'rhodos-resort',
    title: 'All-inclusive resort Rhodos',
    destination: 'Rhodos, Griekenland',
    hotelName: 'Faliraki Bay Resort',
    sfeer: ['resort', 'comfort', 'allinclusive'],
    aanbieder: 'TUI',
    boardType: 'All-inclusive',
    vluchtduur: '3u45',
    adultsOnly: true,
    audience: 'couples',
    matchReason: 'Griekenland op z\'n relaxts',
    whyThisTrip: 'Adults-only all-inclusive aan de Egeïsche Zee — middagdutje, cocktail, herhaal.',
    tags: ['resort', 'allinclusive', 'adults-only', 'strand', 'pool'],
    highlights: ['Privéstrand', 'Adults-only pool', 'Inclusief drankjes & snacks'],
    description: 'Rhodos combineert Grieks karakter met comfortabele all-inclusive service. Dit adults-only resort is gemaakt voor koppels die echt willen loskoppelen.',
    imageUrl: 'https://images.unsplash.com/photo-1586861203927-800a5acdce4d?w=800&q=80',
    affiliatePartner: 'TUI',
    variants: [
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 749,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/griekenland/rhodos/' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 949,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/griekenland/rhodos/' },
      { maand: 'juli',     duur: 7,  airport: 'AMS', prijs: 1149, affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/griekenland/rhodos/' },
      { maand: 'augustus', duur: 7,  airport: 'AMS', prijs: 1249, affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/griekenland/rhodos/' },
      { maand: 'september',duur: 7,  airport: 'AMS', prijs: 899,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/griekenland/rhodos/' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── KOS ──────────────────────────────────────────────────────────────────
  {
    id: 'kos-actief-strand',
    title: 'Actieve strandvakantie Kos',
    destination: 'Kos, Griekenland',
    hotelName: 'Tigaki Beach Studios',
    sfeer: ['actief', 'strand', 'natuur'],
    aanbieder: 'D-reizen',
    boardType: 'Ontbijt',
    vluchtduur: '3u30',
    adultsOnly: false,
    audience: 'couples',
    matchReason: 'Fietsen, strand en authentiek Grieks eten',
    whyThisTrip: 'Kos is het fietseiland van Griekenland — flat, groen en omringd door kristalhelder water.',
    tags: ['actief', 'fietsen', 'strand', 'natuur', 'eten'],
    highlights: ['Plat eiland, ideaal voor fietsen', 'Tigaki strand: kite & wind', 'Lokaal eten in Kos-stad'],
    description: 'Kos is compacter en rustiger dan Rhodos. Perfect voor koppels die actief willen zijn maar ook gewoon op het strand willen liggen.',
    imageUrl: 'https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?w=800&q=80',
    affiliatePartner: 'D-reizen',
    variants: [
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 649,  affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/griekenland/kos' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 799,  affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/griekenland/kos' },
      { maand: 'juli',     duur: 7,  airport: 'AMS', prijs: 999,  affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/griekenland/kos' },
      { maand: 'augustus', duur: 7,  airport: 'AMS', prijs: 1099, affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/griekenland/kos' },
      { maand: 'september',duur: 7,  airport: 'AMS', prijs: 749,  affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/griekenland/kos' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── CORFU ────────────────────────────────────────────────────────────────
  {
    id: 'corfu-relax',
    title: 'Rustige strandweek Corfu',
    destination: 'Corfu, Griekenland',
    hotelName: 'Paleokastritsa Bay Hotel',
    sfeer: ['strand', 'rustig', 'zon'],
    aanbieder: 'Sunweb',
    boardType: 'Halfpension',
    vluchtduur: '3u',
    adultsOnly: false,
    audience: 'couples',
    matchReason: 'Groene heuvels, turquoise baaien — het mooiste van Griekenland',
    whyThisTrip: 'Corfu is groener en romantischer dan de meeste Griekse eilanden — perfect voor koppels.',
    tags: ['strand', 'rustig', 'romantisch', 'natuur', 'halfpension'],
    highlights: ['Paleokastritsa: mooiste baai van Griekenland', 'Groen en bergachtig', 'Kleiner en rustiger'],
    description: 'Corfu combineert weelderig groen met schitterend blauw water. Minder massa, meer sfeer — ideaal voor een romantische week weg.',
    imageUrl: 'https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=800&q=80',
    affiliatePartner: 'Sunweb',
    variants: [
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 649,  affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/corfu' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 799,  affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/corfu' },
      { maand: 'juli',     duur: 7,  airport: 'AMS', prijs: 999,  affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/corfu' },
      { maand: 'september',duur: 7,  airport: 'AMS', prijs: 749,  affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/corfu' },
      { maand: 'mei',      duur: 10, airport: 'AMS', prijs: 899,  affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/corfu' },
      { maand: 'juni',     duur: 10, airport: 'AMS', prijs: 1049, affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/corfu' },
      { maand: 'mei',      duur: 14, airport: 'AMS', prijs: 1099, affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/corfu' },
      { maand: 'juni',     duur: 14, airport: 'AMS', prijs: 1299, affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/corfu' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── ANTALYA / TURKIJE ────────────────────────────────────────────────────
  {
    id: 'antalya-allinclusive',
    title: 'All-inclusive resort Antalya',
    destination: 'Antalya, Turkije',
    hotelName: 'Belek Beach Palace',
    sfeer: ['resort', 'comfort', 'allinclusive'],
    aanbieder: 'Corendon',
    boardType: 'All-inclusive',
    vluchtduur: '3u45',
    adultsOnly: false,
    audience: 'couples',
    matchReason: 'Meeste waarde voor je geld in de Middellandse Zee',
    whyThisTrip: 'Turkije all-inclusive: uitstekende kwaliteit voor de prijs, groot resortcomplex, warm water.',
    tags: ['resort', 'allinclusive', 'strand', 'pool', 'watersport'],
    highlights: ['Privéstrand & meerdere pools', 'Inclusief alles: eten, drinken, sport', 'Warm water tot oktober'],
    description: 'Antalya is de all-inclusive hoofdstad van de Middellandse Zee. Grote resorts, perfect onderhouden stranden en uitstekende service voor een scherpe prijs.',
    imageUrl: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&q=80',
    affiliatePartner: 'Corendon',
    variants: [
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 649,  affiliateUrl: 'https://www.corendon.nl/vakantie/turkije/antalya' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 799,  affiliateUrl: 'https://www.corendon.nl/vakantie/turkije/antalya' },
      { maand: 'juli',     duur: 7,  airport: 'AMS', prijs: 999,  affiliateUrl: 'https://www.corendon.nl/vakantie/turkije/antalya' },
      { maand: 'augustus', duur: 7,  airport: 'AMS', prijs: 1099, affiliateUrl: 'https://www.corendon.nl/vakantie/turkije/antalya' },
      { maand: 'september',duur: 7,  airport: 'AMS', prijs: 849,  affiliateUrl: 'https://www.corendon.nl/vakantie/turkije/antalya' },
      { maand: 'oktober',  duur: 7,  airport: 'AMS', prijs: 699,  affiliateUrl: 'https://www.corendon.nl/vakantie/turkije/antalya' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── BODRUM / TURKIJE ─────────────────────────────────────────────────────
  {
    id: 'bodrum-actief',
    title: 'Actieve week Bodrum',
    destination: 'Bodrum, Turkije',
    hotelName: 'Aegean View Boutique',
    sfeer: ['actief', 'strand', 'natuur'],
    aanbieder: 'TUI',
    boardType: 'Halfpension',
    vluchtduur: '3u30',
    adultsOnly: false,
    audience: 'couples',
    matchReason: 'Zeilen, snorkelen en Turkse cultuur',
    whyThisTrip: 'Bodrum heeft een levendige haven, mooie baaien en de beste watersportmogelijkheden van Turkije.',
    tags: ['actief', 'zeilen', 'snorkelen', 'strand', 'cultuur'],
    highlights: ['Bodrum kasteel & haven', 'Dagtripje per boot', 'Lokale bazaar'],
    description: 'Bodrum is hip, actief en mooi. Overdag op het water, \'s avonds langs de haven flaneren — perfecte mix voor een avontuurlijk koppel.',
    imageUrl: 'https://images.unsplash.com/photo-1580502304784-8985b7eb7260?w=800&q=80',
    affiliatePartner: 'TUI',
    variants: [
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 699,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/turkije/bodrum/' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 849,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/turkije/bodrum/' },
      { maand: 'juli',     duur: 7,  airport: 'AMS', prijs: 1049, affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/turkije/bodrum/' },
      { maand: 'augustus', duur: 7,  airport: 'AMS', prijs: 1149, affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/turkije/bodrum/' },
      { maand: 'september',duur: 7,  airport: 'AMS', prijs: 849,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/turkije/bodrum/' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── CYPRUS ───────────────────────────────────────────────────────────────
  {
    id: 'cyprus-resort-adults',
    title: 'Adults-only resort Cyprus',
    destination: 'Cyprus',
    hotelName: 'Nissi Beach Retreat',
    sfeer: ['resort', 'comfort', 'strand'],
    aanbieder: 'TUI',
    boardType: 'Halfpension',
    vluchtduur: '4u30',
    adultsOnly: true,
    audience: 'couples',
    matchReason: 'Langste strandseizoen van de Middellandse Zee',
    whyThisTrip: 'Cyprus heeft tot eind oktober warm water. Adults-only hotel aan het beroemde Nissi Beach.',
    tags: ['adults-only', 'strand', 'resort', 'zon', 'lang-seizoen'],
    highlights: ['Nissi Beach: top 10 Europa', 'Warm water tot nov', 'Rustig en volwassen sfeer'],
    description: 'Cyprus is de onderschatte parel van de Middellandse Zee. Warm, mooi en minder druk dan Griekenland — perfect voor een relaxt koppelweekje.',
    imageUrl: 'https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=800&q=80',
    affiliatePartner: 'TUI',
    variants: [
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 799,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/cyprus/' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 949,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/cyprus/' },
      { maand: 'juli',     duur: 7,  airport: 'AMS', prijs: 1149, affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/cyprus/' },
      { maand: 'augustus', duur: 7,  airport: 'AMS', prijs: 1249, affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/cyprus/' },
      { maand: 'september',duur: 7,  airport: 'AMS', prijs: 999,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/cyprus/' },
      { maand: 'oktober',  duur: 7,  airport: 'AMS', prijs: 849,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/cyprus/' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── ALGARVE / PORTUGAL ───────────────────────────────────────────────────
  {
    id: 'algarve-actief',
    title: 'Actieve kustweek Algarve',
    destination: 'Algarve, Portugal',
    hotelName: 'Lagos Cliffs Boutique Hotel',
    sfeer: ['actief', 'natuur', 'strand'],
    aanbieder: 'Sunweb',
    boardType: 'Ontbijt',
    vluchtduur: '2u45',
    adultsOnly: false,
    audience: 'couples',
    matchReason: 'Spectaculaire rotskusten en verborgen stranden',
    whyThisTrip: 'De Algarve heeft de mooiste kustlijn van Europa — perfect voor koppels die graag wandelen en ontdekken.',
    tags: ['actief', 'wandelen', 'rotskusten', 'strand', 'natuur'],
    highlights: ['Ponta da Piedade: iconische rotsformaties', 'Kajakken langs de kust', 'Verse vis & wine'],
    description: 'De Algarve is anders dan de gemiddelde zonvakantie. Ruige kliffen, gouden stranden en heerlijk eten. Perfect voor actieve koppels die ook willen relaxen.',
    imageUrl: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80',
    affiliatePartner: 'Sunweb',
    variants: [
      { maand: 'april',    duur: 7,  airport: 'AMS', prijs: 699,  affiliateUrl: 'https://www.sunweb.nl/vakantie/portugal/algarve' },
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 749,  affiliateUrl: 'https://www.sunweb.nl/vakantie/portugal/algarve' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 849,  affiliateUrl: 'https://www.sunweb.nl/vakantie/portugal/algarve' },
      { maand: 'juli',     duur: 7,  airport: 'AMS', prijs: 999,  affiliateUrl: 'https://www.sunweb.nl/vakantie/portugal/algarve' },
      { maand: 'augustus', duur: 7,  airport: 'AMS', prijs: 1099, affiliateUrl: 'https://www.sunweb.nl/vakantie/portugal/algarve' },
      { maand: 'september',duur: 7,  airport: 'AMS', prijs: 849,  affiliateUrl: 'https://www.sunweb.nl/vakantie/portugal/algarve' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── HURGHADA / EGYPTE ────────────────────────────────────────────────────
  {
    id: 'hurghada-allinclusive',
    title: 'All-inclusive Hurghada',
    destination: 'Hurghada, Egypte',
    hotelName: 'Makadi Bay Palace',
    sfeer: ['resort', 'comfort', 'allinclusive'],
    aanbieder: 'Corendon',
    boardType: 'All-inclusive',
    vluchtduur: '5u',
    adultsOnly: false,
    audience: 'couples',
    matchReason: 'Snorkelen én all-inclusive voor een scherpe prijs',
    whyThisTrip: 'Hurghada combineert geweldig snorkelen in de Rode Zee met uitstekende all-inclusive resorts.',
    tags: ['resort', 'allinclusive', 'snorkelen', 'duiken', 'rode-zee'],
    highlights: ['Koraalrif voor de kust', 'All-inclusive inclusief watersport', 'Budget-vriendelijkste optie'],
    description: 'Voor koppels die het maximale willen voor hun budget. Warm water, kleurrijke koraalriffen en alles inclusief. Hurghada is een uitstekende keuze buiten het hoogseizoen.',
    imageUrl: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
    affiliatePartner: 'Corendon',
    variants: [
      { maand: 'januari',  duur: 7,  airport: 'AMS', prijs: 699,  affiliateUrl: 'https://www.corendon.nl/vakantie/egypte/hurghada' },
      { maand: 'februari', duur: 7,  airport: 'AMS', prijs: 699,  affiliateUrl: 'https://www.corendon.nl/vakantie/egypte/hurghada' },
      { maand: 'maart',    duur: 7,  airport: 'AMS', prijs: 649,  affiliateUrl: 'https://www.corendon.nl/vakantie/egypte/hurghada' },
      { maand: 'april',    duur: 7,  airport: 'AMS', prijs: 649,  affiliateUrl: 'https://www.corendon.nl/vakantie/egypte/hurghada' },
      { maand: 'oktober',  duur: 7,  airport: 'AMS', prijs: 699,  affiliateUrl: 'https://www.corendon.nl/vakantie/egypte/hurghada' },
      { maand: 'november', duur: 7,  airport: 'AMS', prijs: 649,  affiliateUrl: 'https://www.corendon.nl/vakantie/egypte/hurghada' },
      { maand: 'december', duur: 7,  airport: 'AMS', prijs: 749,  affiliateUrl: 'https://www.corendon.nl/vakantie/egypte/hurghada' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── LANZAROTE ────────────────────────────────────────────────────────────
  {
    id: 'lanzarote-actief',
    title: 'Actieve vulkaanweek Lanzarote',
    destination: 'Lanzarote, Spanje',
    hotelName: 'Playa Blanca Surf Lodge',
    sfeer: ['actief', 'natuur', 'strand'],
    aanbieder: 'D-reizen',
    boardType: 'Ontbijt',
    vluchtduur: '3u45',
    adultsOnly: false,
    audience: 'couples',
    matchReason: 'Vulkaanlandschap, surfen en wilde kusten',
    whyThisTrip: 'Lanzarote is het meest bijzondere Canarische eiland — zwarte lava, windmolens en uitstekende surfspots.',
    tags: ['actief', 'surfen', 'natuur', 'vulkaan', 'windsurf'],
    highlights: ['Timanfaya nationaalpark', 'Famara: surfstrand', 'Jamieos del Agua'],
    description: 'Lanzarote is niet voor iedereen — maar voor koppels die avontuur zoeken is het een van de mooiste bestemmingen van Europa.',
    imageUrl: 'https://images.unsplash.com/photo-1564415092735-e8a1b64da5b7?w=800&q=80',
    affiliatePartner: 'D-reizen',
    variants: [
      { maand: 'maart',    duur: 7,  airport: 'AMS', prijs: 699,  affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/spanje/lanzarote' },
      { maand: 'april',    duur: 7,  airport: 'AMS', prijs: 749,  affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/spanje/lanzarote' },
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 749,  affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/spanje/lanzarote' },
      { maand: 'oktober',  duur: 7,  airport: 'AMS', prijs: 749,  affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/spanje/lanzarote' },
      { maand: 'november', duur: 7,  airport: 'AMS', prijs: 699,  affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/spanje/lanzarote' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── IBIZA ────────────────────────────────────────────────────────────────
  {
    id: 'ibiza-relax-noorden',
    title: 'Rustig Ibiza (noorden)',
    destination: 'Ibiza, Spanje',
    hotelName: 'Cala San Vicente Retreat',
    sfeer: ['strand', 'rustig', 'zon'],
    aanbieder: 'TUI',
    boardType: 'Ontbijt',
    vluchtduur: '2u30',
    adultsOnly: false,
    audience: 'couples',
    matchReason: 'Ibiza zonder het feestgeweld — rustige baaien en geweldig eten',
    whyThisTrip: 'Het noorden van Ibiza is een wereld apart: rustig, authentiek en schitterend mooi.',
    tags: ['strand', 'rustig', 'eten', 'romantisch', 'ontbijt'],
    highlights: ['Cala San Vicente: rustige baai', 'Authentieke dorpjes', 'Beste restaurants van Ibiza'],
    description: 'Ibiza is meer dan clubs en feesten. Het noorden is groen, rustig en authentiek. Een perfecte keuze voor koppels die willen ontsnappen aan de massa.',
    imageUrl: 'https://images.unsplash.com/photo-1510525009512-ad7fc13eaf09?w=800&q=80',
    affiliatePartner: 'TUI',
    variants: [
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 749,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/ibiza/' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 949,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/ibiza/' },
      { maand: 'september',duur: 7,  airport: 'AMS', prijs: 899,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/ibiza/' },
      { maand: 'mei',      duur: 10, airport: 'AMS', prijs: 999,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/ibiza/' },
      { maand: 'juni',     duur: 10, airport: 'AMS', prijs: 1249, affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/ibiza/' },
      { maand: 'mei',      duur: 14, airport: 'AMS', prijs: 1249, affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/ibiza/' },
      { maand: 'september',duur: 14, airport: 'AMS', prijs: 1449, affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/ibiza/' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── FUERTEVENTURA ────────────────────────────────────────────────────
  {
    id: 'fuerteventura-strand',
    title: 'Strandweek Fuerteventura',
    destination: 'Fuerteventura, Spanje',
    hotelName: 'Costa Calma Beach Hotel',
    sfeer: ['strand', 'rustig', 'zon'],
    aanbieder: 'Sunweb',
    boardType: 'Halfpension',
    vluchtduur: '4u',
    adultsOnly: false,
    audience: 'couples',
    matchReason: 'Eindeloze witte stranden zonder drukte',
    whyThisTrip: 'Fuerteventura heeft de langste en breedste stranden van de Canarische Eilanden — rust gegarandeerd.',
    tags: ['strand', 'rustig', 'zon', 'wind', 'ruimte'],
    highlights: ['30 km witte stranden', 'Weinig toeristen', 'Halfpension inclusief'],
    description: 'Fuerteventura is het rustigste Canarische eiland. Eindeloze stranden, weinig bebouwing en een relaxte vibe.',
    imageUrl: 'https://images.unsplash.com/photo-1585255318859-f5c15f4cffe9?w=800&q=80',
    affiliatePartner: 'Sunweb',
    variants: [
      { maand: 'april',    duur: 7,  airport: 'AMS', prijs: 699,  affiliateUrl: 'https://www.sunweb.nl/vakantie/spanje/fuerteventura' },
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 699,  affiliateUrl: 'https://www.sunweb.nl/vakantie/spanje/fuerteventura' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 799,  affiliateUrl: 'https://www.sunweb.nl/vakantie/spanje/fuerteventura' },
      { maand: 'september',duur: 7,  airport: 'AMS', prijs: 749,  affiliateUrl: 'https://www.sunweb.nl/vakantie/spanje/fuerteventura' },
      { maand: 'oktober',  duur: 7,  airport: 'AMS', prijs: 699,  affiliateUrl: 'https://www.sunweb.nl/vakantie/spanje/fuerteventura' },
      { maand: 'mei',      duur: 10, airport: 'AMS', prijs: 949,  affiliateUrl: 'https://www.sunweb.nl/vakantie/spanje/fuerteventura' },
      { maand: 'oktober',  duur: 10, airport: 'AMS', prijs: 949,  affiliateUrl: 'https://www.sunweb.nl/vakantie/spanje/fuerteventura' },
      { maand: 'mei',      duur: 14, airport: 'AMS', prijs: 1149, affiliateUrl: 'https://www.sunweb.nl/vakantie/spanje/fuerteventura' },
      { maand: 'oktober',  duur: 14, airport: 'AMS', prijs: 1149, affiliateUrl: 'https://www.sunweb.nl/vakantie/spanje/fuerteventura' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── COSTA BRAVA ──────────────────────────────────────────────────────
  {
    id: 'costa-brava-actief',
    title: 'Actieve kustweek Costa Brava',
    destination: 'Costa Brava, Spanje',
    hotelName: 'Tossa Beach Boutique',
    sfeer: ['actief', 'natuur', 'strand'],
    aanbieder: 'TUI',
    boardType: 'Ontbijt',
    vluchtduur: '2u',
    adultsOnly: false,
    audience: 'couples',
    matchReason: 'Dichtbij, mooi en verrassend veel te doen',
    whyThisTrip: 'Kajakken langs rotsige kusten, wandelen door vissersdorpjes en genieten van Catalaans eten.',
    tags: ['actief', 'strand', 'natuur', 'kajakken', 'eten'],
    highlights: ['Camí de Ronda kustpad', 'Kayak excursies', 'Catalaans eten'],
    description: 'De Costa Brava is meer dan massatoerisme. Het noorden heeft schitterende baaien, verborgen grotten en uitstekende restaurants.',
    imageUrl: 'https://images.unsplash.com/photo-1583946099379-f9c9cb8bc030?w=800&q=80',
    affiliatePartner: 'TUI',
    variants: [
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 599,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/costa-brava/' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 749,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/costa-brava/' },
      { maand: 'juli',     duur: 7,  airport: 'AMS', prijs: 899,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/costa-brava/' },
      { maand: 'september',duur: 7,  airport: 'AMS', prijs: 749,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/costa-brava/' },
      { maand: 'juni',     duur: 10, airport: 'AMS', prijs: 999,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/costa-brava/' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── ZAKYNTHOS ────────────────────────────────────────────────────────
  {
    id: 'zakynthos-strand',
    title: 'Strandparadijs Zakynthos',
    destination: 'Zakynthos, Griekenland',
    hotelName: 'Laganas Bay Resort',
    sfeer: ['strand', 'rustig', 'zon'],
    aanbieder: 'D-reizen',
    boardType: 'All-inclusive',
    vluchtduur: '3u',
    adultsOnly: false,
    audience: 'couples',
    matchReason: 'Beroemd om Navagio Beach — adembenemend mooi',
    whyThisTrip: 'Zakynthos heeft het beroemdste strand van Griekenland en kristalhelder water overal.',
    tags: ['strand', 'zon', 'rustig', 'allinclusive', 'fotogeniek'],
    highlights: ['Navagio (Shipwreck) Beach', 'Schildpadden spotten', 'Kleine eilandsfeer'],
    description: 'Zakynthos is compact maar spectaculair. De blauwe grotten en het iconische Navagio strand maken het onvergetelijk.',
    imageUrl: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80',
    affiliatePartner: 'D-reizen',
    variants: [
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 699,  affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/griekenland/zakynthos' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 849,  affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/griekenland/zakynthos' },
      { maand: 'juli',     duur: 7,  airport: 'AMS', prijs: 999,  affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/griekenland/zakynthos' },
      { maand: 'augustus', duur: 7,  airport: 'AMS', prijs: 1099, affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/griekenland/zakynthos' },
      { maand: 'september',duur: 7,  airport: 'AMS', prijs: 799,  affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/griekenland/zakynthos' },
      { maand: 'juni',     duur: 10, airport: 'AMS', prijs: 1099, affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/griekenland/zakynthos' },
      { maand: 'mei',      duur: 14, airport: 'AMS', prijs: 1199, affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/griekenland/zakynthos' },
      { maand: 'juni',     duur: 14, airport: 'AMS', prijs: 1399, affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/griekenland/zakynthos' },
      { maand: 'september',duur: 14, airport: 'AMS', prijs: 1299, affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/griekenland/zakynthos' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── SARDINIË ─────────────────────────────────────────────────────────
  {
    id: 'sardinie-actief',
    title: 'Actieve week Sardinië',
    destination: 'Sardinië, Italië',
    hotelName: 'Costa Smeralda Lodge',
    sfeer: ['actief', 'natuur', 'strand'],
    aanbieder: 'Sunweb',
    boardType: 'Ontbijt',
    vluchtduur: '2u30',
    adultsOnly: false,
    audience: 'couples',
    matchReason: 'Caribisch water in Europa — met Italiaans eten erbij',
    whyThisTrip: 'Sardinië heeft het helderste water van de Middellandse Zee en spectaculaire wandelpaden langs de kust.',
    tags: ['actief', 'strand', 'natuur', 'eten', 'wandelen'],
    highlights: ['Smaragdgroene baaien', 'Pasta & pesce overal', 'Trekking langs de kust'],
    description: 'Sardinië is Italië op z\'n mooist. Wilde natuur, Caribisch-achtig water en authentiek Italiaans eten.',
    imageUrl: 'https://images.unsplash.com/photo-1586015555751-63bb77f4322a?w=800&q=80',
    affiliatePartner: 'Sunweb',
    variants: [
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 749,  affiliateUrl: 'https://www.sunweb.nl/vakantie/italie/sardinie' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 899,  affiliateUrl: 'https://www.sunweb.nl/vakantie/italie/sardinie' },
      { maand: 'juli',     duur: 7,  airport: 'AMS', prijs: 1099, affiliateUrl: 'https://www.sunweb.nl/vakantie/italie/sardinie' },
      { maand: 'september',duur: 7,  airport: 'AMS', prijs: 849,  affiliateUrl: 'https://www.sunweb.nl/vakantie/italie/sardinie' },
      { maand: 'juni',     duur: 14, airport: 'AMS', prijs: 1499, affiliateUrl: 'https://www.sunweb.nl/vakantie/italie/sardinie' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── SICILIË ──────────────────────────────────────────────────────────
  {
    id: 'sicilie-resort',
    title: 'Resort & cultuur Sicilië',
    destination: 'Sicilië, Italië',
    hotelName: 'Taormina Palace',
    sfeer: ['resort', 'comfort', 'strand'],
    aanbieder: 'TUI',
    boardType: 'Halfpension',
    vluchtduur: '2u45',
    adultsOnly: true,
    audience: 'couples',
    matchReason: 'Luxe resort met Siciliaanse cultuur op loopafstand',
    whyThisTrip: 'Taormina is het mooiste stadje van Sicilië — Grieks theater, uitzicht op de Etna en fantastisch eten.',
    tags: ['resort', 'comfort', 'adults-only', 'eten', 'cultuur'],
    highlights: ['Uitzicht op de Etna', 'Teatro Greco', 'Siciliaans eten'],
    description: 'Sicilië combineert stranden met een rijke geschiedenis. Dit adults-only resort in Taormina is de perfecte uitvalsbasis.',
    imageUrl: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=800&q=80',
    affiliatePartner: 'TUI',
    variants: [
      { maand: 'april',    duur: 7,  airport: 'AMS', prijs: 799,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/italie/sicilie/' },
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 899,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/italie/sicilie/' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 1049, affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/italie/sicilie/' },
      { maand: 'september',duur: 7,  airport: 'AMS', prijs: 949,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/italie/sicilie/' },
      { maand: 'oktober',  duur: 7,  airport: 'AMS', prijs: 849,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/italie/sicilie/' },
      { maand: 'mei',      duur: 10, airport: 'AMS', prijs: 1199, affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/italie/sicilie/' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── MENORCA ──────────────────────────────────────────────────────────
  {
    id: 'menorca-strand-relax',
    title: 'Rustig strandweekje Menorca',
    destination: 'Menorca, Spanje',
    hotelName: 'Cala Galdana Beach Hotel',
    sfeer: ['strand', 'rustig', 'zon'],
    aanbieder: 'Corendon',
    boardType: 'Halfpension',
    vluchtduur: '2u15',
    adultsOnly: false,
    audience: 'couples',
    matchReason: 'Ibiza\'s rustige zusje — zonder de drukte',
    whyThisTrip: 'Menorca is een UNESCO-biosfeerreservaat met ongerepte baaien en een relaxte sfeer.',
    tags: ['strand', 'rustig', 'zon', 'natuur', 'authentiek'],
    highlights: ['UNESCO biosfeerreservaat', 'Ongerepte calas', 'Geen massatoerisme'],
    description: 'Menorca is het best bewaarde geheim van de Balearen. Schitterende stranden, authentieke dorpjes en absolute rust.',
    imageUrl: 'https://images.unsplash.com/photo-1563784462386-044fd95e9852?w=800&q=80',
    affiliatePartner: 'Corendon',
    variants: [
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 699,  affiliateUrl: 'https://www.corendon.nl/vakantie/spanje/menorca' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 849,  affiliateUrl: 'https://www.corendon.nl/vakantie/spanje/menorca' },
      { maand: 'juli',     duur: 7,  airport: 'AMS', prijs: 1049, affiliateUrl: 'https://www.corendon.nl/vakantie/spanje/menorca' },
      { maand: 'september',duur: 7,  airport: 'AMS', prijs: 799,  affiliateUrl: 'https://www.corendon.nl/vakantie/spanje/menorca' },
      { maand: 'mei',      duur: 10, airport: 'AMS', prijs: 949,  affiliateUrl: 'https://www.corendon.nl/vakantie/spanje/menorca' },
      { maand: 'juni',     duur: 10, airport: 'AMS', prijs: 1099, affiliateUrl: 'https://www.corendon.nl/vakantie/spanje/menorca' },
      { maand: 'mei',      duur: 14, airport: 'AMS', prijs: 1149, affiliateUrl: 'https://www.corendon.nl/vakantie/spanje/menorca' },
      { maand: 'september',duur: 14, airport: 'AMS', prijs: 1299, affiliateUrl: 'https://www.corendon.nl/vakantie/spanje/menorca' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── COSTA DEL SOL ────────────────────────────────────────────────────
  {
    id: 'costa-del-sol-resort',
    title: 'All-inclusive Costa del Sol',
    destination: 'Costa del Sol, Spanje',
    hotelName: 'Marbella Playa Resort',
    sfeer: ['resort', 'comfort', 'allinclusive'],
    aanbieder: 'TUI',
    boardType: 'All-inclusive',
    vluchtduur: '2u45',
    adultsOnly: false,
    audience: 'couples',
    matchReason: 'Klassieke Spaanse zonvakantie met uitstekende service',
    whyThisTrip: 'De Costa del Sol heeft het meeste aantal zonuren van Spanje. Betrouwbaar, comfortabel en lekker eten.',
    tags: ['resort', 'allinclusive', 'strand', 'zon', 'comfort'],
    highlights: ['320 zondagen per jaar', 'Tapas & wijn inbegrepen', 'Strand op 50m'],
    description: 'De Costa del Sol is een betrouwbare keuze voor koppels die gewoon lekker in de zon willen liggen met alles inbegrepen.',
    imageUrl: 'https://images.unsplash.com/photo-1549880181-56a44cf4a9a5?w=800&q=80',
    affiliatePartner: 'TUI',
    variants: [
      { maand: 'april',    duur: 7,  airport: 'AMS', prijs: 649,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/costa-del-sol/' },
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 749,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/costa-del-sol/' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 899,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/costa-del-sol/' },
      { maand: 'juli',     duur: 7,  airport: 'AMS', prijs: 1049, affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/costa-del-sol/' },
      { maand: 'september',duur: 7,  airport: 'AMS', prijs: 849,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/costa-del-sol/' },
      { maand: 'oktober',  duur: 7,  airport: 'AMS', prijs: 699,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/costa-del-sol/' },
      { maand: 'mei',      duur: 14, airport: 'AMS', prijs: 1299, affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/spanje/costa-del-sol/' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── KAAPVERDIË ───────────────────────────────────────────────────────
  {
    id: 'kaapverdie-strand',
    title: 'Strandweek Kaapverdië',
    destination: 'Sal, Kaapverdië',
    hotelName: 'Santa Maria Beach Resort',
    sfeer: ['strand', 'rustig', 'zon'],
    aanbieder: 'Corendon',
    boardType: 'All-inclusive',
    vluchtduur: '6u',
    adultsOnly: false,
    audience: 'couples',
    matchReason: 'Caribisch gevoel, zonder de jetlag',
    whyThisTrip: 'Kaapverdië heeft wit strand, warm water en een relaxte Afrikaanse sfeer — op 6 uur vliegen.',
    tags: ['strand', 'rustig', 'zon', 'allinclusive', 'exotisch'],
    highlights: ['30°C het hele jaar', 'Wit zandstrand', 'All-inclusive resort'],
    description: 'Kaapverdië is de perfecte escape: ver genoeg om exotisch te voelen, dichtbij genoeg om het betaalbaar te houden.',
    imageUrl: 'https://images.unsplash.com/photo-1590523741831-ab7e8b8f9c7f?w=800&q=80',
    affiliatePartner: 'Corendon',
    variants: [
      { maand: 'april',    duur: 7,  airport: 'AMS', prijs: 899,  affiliateUrl: 'https://www.corendon.nl/vakantie/kaapverdie' },
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 849,  affiliateUrl: 'https://www.corendon.nl/vakantie/kaapverdie' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 899,  affiliateUrl: 'https://www.corendon.nl/vakantie/kaapverdie' },
      { maand: 'oktober',  duur: 7,  airport: 'AMS', prijs: 899,  affiliateUrl: 'https://www.corendon.nl/vakantie/kaapverdie' },
      { maand: 'mei',      duur: 10, airport: 'AMS', prijs: 1149, affiliateUrl: 'https://www.corendon.nl/vakantie/kaapverdie' },
      { maand: 'april',    duur: 14, airport: 'AMS', prijs: 1449, affiliateUrl: 'https://www.corendon.nl/vakantie/kaapverdie' },
      { maand: 'mei',      duur: 14, airport: 'AMS', prijs: 1399, affiliateUrl: 'https://www.corendon.nl/vakantie/kaapverdie' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── KROATIË / DUBROVNIK ──────────────────────────────────────────────
  {
    id: 'dubrovnik-actief',
    title: 'Actieve week Dubrovnik',
    destination: 'Dubrovnik, Kroatië',
    hotelName: 'Lapad Beach Hotel',
    sfeer: ['actief', 'natuur', 'strand'],
    aanbieder: 'D-reizen',
    boardType: 'Ontbijt',
    vluchtduur: '2u15',
    adultsOnly: false,
    audience: 'couples',
    matchReason: 'Historische stadsmuren, eilandhoppen en helder water',
    whyThisTrip: 'Dubrovnik combineert cultuur, natuur en strand — met een boottochtje naar de Elafiti-eilanden.',
    tags: ['actief', 'strand', 'cultuur', 'eilandhoppen', 'natuur'],
    highlights: ['Stadsmuren wandeling', 'Eilandhoppen per boot', 'Game of Thrones locaties'],
    description: 'Dubrovnik is een van de mooiste steden van Europa. Perfect als uitvalsbasis voor actieve koppels die ook cultuur willen.',
    imageUrl: 'https://images.unsplash.com/photo-1555990793-da11153a3522?w=800&q=80',
    affiliatePartner: 'D-reizen',
    variants: [
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 749,  affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/kroatie/dubrovnik' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 899,  affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/kroatie/dubrovnik' },
      { maand: 'juli',     duur: 7,  airport: 'AMS', prijs: 1099, affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/kroatie/dubrovnik' },
      { maand: 'september',duur: 7,  airport: 'AMS', prijs: 849,  affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/kroatie/dubrovnik' },
      { maand: 'juni',     duur: 10, airport: 'AMS', prijs: 1149, affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/kroatie/dubrovnik' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── SPLIT / KROATIË ──────────────────────────────────────────────────
  {
    id: 'split-resort',
    title: 'Resort aan de Dalmatische kust',
    destination: 'Split, Kroatië',
    hotelName: 'Podstrana Riviera Resort',
    sfeer: ['resort', 'comfort', 'strand'],
    aanbieder: 'Sunweb',
    boardType: 'Halfpension',
    vluchtduur: '2u',
    adultsOnly: true,
    audience: 'couples',
    matchReason: 'Adults-only resort aan de mooiste kust van Kroatië',
    whyThisTrip: 'Podstrana ligt vlak bij Split maar voelt als een rustig toevluchtsoord aan de Adriatische Zee.',
    tags: ['resort', 'comfort', 'adults-only', 'strand', 'halfpension'],
    highlights: ['Privéstrand', 'Oude stad Split op 15 min', 'Adults-only rust'],
    description: 'Split combineert Romeinse geschiedenis met een prachtige kustlijn. Dit adults-only resort biedt het beste van beide.',
    imageUrl: 'https://images.unsplash.com/photo-1580137189272-c9379f8864fd?w=800&q=80',
    affiliatePartner: 'Sunweb',
    variants: [
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 749,  affiliateUrl: 'https://www.sunweb.nl/vakantie/kroatie/split' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 899,  affiliateUrl: 'https://www.sunweb.nl/vakantie/kroatie/split' },
      { maand: 'juli',     duur: 7,  airport: 'AMS', prijs: 1099, affiliateUrl: 'https://www.sunweb.nl/vakantie/kroatie/split' },
      { maand: 'augustus', duur: 7,  airport: 'AMS', prijs: 1199, affiliateUrl: 'https://www.sunweb.nl/vakantie/kroatie/split' },
      { maand: 'september',duur: 7,  airport: 'AMS', prijs: 849,  affiliateUrl: 'https://www.sunweb.nl/vakantie/kroatie/split' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── MONTENEGRO ───────────────────────────────────────────────────────
  {
    id: 'montenegro-actief',
    title: 'Avontuurweek Montenegro',
    destination: 'Budva, Montenegro',
    hotelName: 'Budva Riviera Hotel',
    sfeer: ['actief', 'natuur', 'avontuur'],
    aanbieder: 'D-reizen',
    boardType: 'Ontbijt',
    vluchtduur: '2u15',
    adultsOnly: false,
    audience: 'couples',
    matchReason: 'Opkomende bestemming — mooi, betaalbaar en onontdekt',
    whyThisTrip: 'Montenegro is het best bewaarde geheim van de Adriatische kust — fjorden, bergen en strand in één.',
    tags: ['actief', 'natuur', 'avontuur', 'strand', 'budget'],
    highlights: ['Baai van Kotor (UNESCO)', 'Rafting op de Tara', 'Budva oude stad'],
    description: 'Montenegro is spectaculair en nog betaalbaar. De combinatie van bergen, fjorden en stranden is uniek in Europa.',
    imageUrl: 'https://images.unsplash.com/photo-1584132905271-512c958d674a?w=800&q=80',
    affiliatePartner: 'D-reizen',
    variants: [
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 599,  affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/montenegro' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 749,  affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/montenegro' },
      { maand: 'juli',     duur: 7,  airport: 'AMS', prijs: 899,  affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/montenegro' },
      { maand: 'september',duur: 7,  airport: 'AMS', prijs: 699,  affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/montenegro' },
      { maand: 'juni',     duur: 10, airport: 'AMS', prijs: 999,  affiliateUrl: 'https://www.d-reizen.nl/zonvakantie/montenegro' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── MARRAKECH / MAROKKO ──────────────────────────────────────────────
  {
    id: 'marrakech-resort',
    title: 'Resort met pool Marrakech',
    destination: 'Marrakech, Marokko',
    hotelName: 'Atlas Palmeraie Resort',
    sfeer: ['resort', 'comfort', 'allinclusive'],
    aanbieder: 'Corendon',
    boardType: 'All-inclusive',
    vluchtduur: '3u30',
    adultsOnly: false,
    audience: 'couples',
    matchReason: 'Exotisch en betaalbaar — resort met pool in de palmeraie',
    whyThisTrip: 'Marrakech biedt kleur, cultuur en zon in een all-inclusive formule. De souk is op 20 minuten.',
    tags: ['resort', 'allinclusive', 'zon', 'cultuur', 'exotisch'],
    highlights: ['Pool in de palmeraie', 'Souk & Jemaa el-Fna', 'Hammam in hotel'],
    description: 'Marrakech is anders dan een typische zonvakantie maar minstens zo ontspannend. Resort als basis, medina als avontuur.',
    imageUrl: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800&q=80',
    affiliatePartner: 'Corendon',
    variants: [
      { maand: 'april',    duur: 7,  airport: 'AMS', prijs: 599,  affiliateUrl: 'https://www.corendon.nl/vakantie/marokko/marrakech' },
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 649,  affiliateUrl: 'https://www.corendon.nl/vakantie/marokko/marrakech' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 749,  affiliateUrl: 'https://www.corendon.nl/vakantie/marokko/marrakech' },
      { maand: 'september',duur: 7,  airport: 'AMS', prijs: 699,  affiliateUrl: 'https://www.corendon.nl/vakantie/marokko/marrakech' },
      { maand: 'oktober',  duur: 7,  airport: 'AMS', prijs: 649,  affiliateUrl: 'https://www.corendon.nl/vakantie/marokko/marrakech' },
      { maand: 'mei',      duur: 10, airport: 'AMS', prijs: 849,  affiliateUrl: 'https://www.corendon.nl/vakantie/marokko/marrakech' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── MALTA ────────────────────────────────────────────────────────────
  {
    id: 'malta-actief',
    title: 'Actieve cultuurweek Malta',
    destination: 'Malta',
    hotelName: 'St. Julian\'s Harbour Hotel',
    sfeer: ['actief', 'natuur', 'strand'],
    aanbieder: 'TUI',
    boardType: 'Ontbijt',
    vluchtduur: '3u',
    adultsOnly: false,
    audience: 'couples',
    matchReason: 'Compact eiland boordevol geschiedenis en duikspots',
    whyThisTrip: 'Malta is klein maar heeft meer te bieden per vierkante meter dan bijna elk ander eiland.',
    tags: ['actief', 'duiken', 'cultuur', 'strand', 'natuur'],
    highlights: ['Blauwe Lagune', 'Valletta (UNESCO)', 'Duiken & snorkelen'],
    description: 'Malta combineert 7.000 jaar geschiedenis met helder blauw water. Perfect voor koppels die actief willen zijn maar ook cultuur zoeken.',
    imageUrl: 'https://images.unsplash.com/photo-1557394976-32cc983558ba?w=800&q=80',
    affiliatePartner: 'TUI',
    variants: [
      { maand: 'april',    duur: 7,  airport: 'AMS', prijs: 599,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/malta/' },
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 699,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/malta/' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 849,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/malta/' },
      { maand: 'september',duur: 7,  airport: 'AMS', prijs: 799,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/malta/' },
      { maand: 'oktober',  duur: 7,  airport: 'AMS', prijs: 699,  affiliateUrl: 'https://www.tui.nl/zonnige-bestemmingen/malta/' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── SANTORINI ────────────────────────────────────────────────────────
  {
    id: 'santorini-relax',
    title: 'Romantisch Santorini',
    destination: 'Santorini, Griekenland',
    hotelName: 'Oia Sunset Suites',
    sfeer: ['strand', 'rustig', 'zon'],
    aanbieder: 'Sunweb',
    boardType: 'Ontbijt',
    vluchtduur: '3u30',
    adultsOnly: true,
    audience: 'couples',
    matchReason: 'De meest romantische bestemming van Europa',
    whyThisTrip: 'Witte huisjes, blauwe koepels en de beroemdste zonsondergang ter wereld — gemaakt voor koppels.',
    tags: ['strand', 'rustig', 'romantisch', 'zon', 'adults-only'],
    highlights: ['Zonsondergang in Oia', 'Wijnproeverij', 'Vulkanisch zwart strand'],
    description: 'Santorini is niet goedkoop maar onvergetelijk. De perfecte bestemming voor een bijzondere trip samen.',
    imageUrl: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80',
    affiliatePartner: 'Sunweb',
    variants: [
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 999,  affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/santorini' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 1149, affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/santorini' },
      { maand: 'september',duur: 7,  airport: 'AMS', prijs: 1049, affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/santorini' },
      { maand: 'oktober',  duur: 7,  airport: 'AMS', prijs: 899,  affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/santorini' },
      { maand: 'mei',      duur: 10, airport: 'AMS', prijs: 1299, affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/santorini' },
      { maand: 'september',duur: 10, airport: 'AMS', prijs: 1349, affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/santorini' },
      { maand: 'mei',      duur: 14, airport: 'AMS', prijs: 1599, affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/santorini' },
      { maand: 'september',duur: 14, airport: 'AMS', prijs: 1699, affiliateUrl: 'https://www.sunweb.nl/vakantie/griekenland/santorini' },
    ],
    prijsPeilDatum: 'april 2026',
  },

  // ── TENERIFE RESORT ──────────────────────────────────────────────────
  {
    id: 'tenerife-resort',
    title: 'All-inclusive resort Tenerife',
    destination: 'Tenerife, Spanje',
    hotelName: 'Costa Adeje Palace',
    sfeer: ['resort', 'comfort', 'allinclusive'],
    aanbieder: 'Corendon',
    boardType: 'All-inclusive',
    vluchtduur: '4u15',
    adultsOnly: true,
    audience: 'couples',
    matchReason: 'Luxe adults-only resort met het hele jaar zon',
    whyThisTrip: 'Costa Adeje is het meest luxe deel van Tenerife. Adults-only resort met geweldig eten en een infinity pool.',
    tags: ['resort', 'allinclusive', 'adults-only', 'pool', 'comfort'],
    highlights: ['Infinity pool met zeezicht', 'Adults-only restaurant', 'Walvissen spotten'],
    description: 'Tenerife voor de liefhebber van comfort. Dit resort in Costa Adeje biedt luxe zonder de prijs van de Malediven.',
    imageUrl: 'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80',
    affiliatePartner: 'Corendon',
    variants: [
      { maand: 'april',    duur: 7,  airport: 'AMS', prijs: 899,  affiliateUrl: 'https://www.corendon.nl/vakantie/tenerife' },
      { maand: 'mei',      duur: 7,  airport: 'AMS', prijs: 899,  affiliateUrl: 'https://www.corendon.nl/vakantie/tenerife' },
      { maand: 'juni',     duur: 7,  airport: 'AMS', prijs: 999,  affiliateUrl: 'https://www.corendon.nl/vakantie/tenerife' },
      { maand: 'september',duur: 7,  airport: 'AMS', prijs: 999,  affiliateUrl: 'https://www.corendon.nl/vakantie/tenerife' },
      { maand: 'oktober',  duur: 7,  airport: 'AMS', prijs: 899,  affiliateUrl: 'https://www.corendon.nl/vakantie/tenerife' },
      { maand: 'mei',      duur: 14, airport: 'AMS', prijs: 1549, affiliateUrl: 'https://www.corendon.nl/vakantie/tenerife' },
    ],
    prijsPeilDatum: 'april 2026',
  },

];

// Helper: match de juiste variant op basis van gebruikersvoorkeuren
function matchVariant(trip, prefs) {
  return trip.variants.find(v =>
    prefs.maanden.includes(v.maand) &&
    v.duur === prefs.duur &&
    v.airport === prefs.airport &&
    v.prijs <= prefs.budgetMax
  ) || null;
}

// Helper: filter trips op sfeer-tags
function filterTrips(prefs) {
  return trips
    .map(trip => {
      const variant = matchVariant(trip, prefs);
      if (!variant) return null;
      // Check sfeer overlap
      const sfeermatch = trip.sfeer.some(s => prefs.sfeer.includes(s));
      if (!sfeermatch) return null;
      return { ...trip, matchedVariant: variant };
    })
    .filter(Boolean)
    .sort((a, b) => {
      // Sorteer: meeste sfeer-overlap bovenaan
      const scoreA = a.sfeer.filter(s => prefs.sfeer.includes(s)).length;
      const scoreB = b.sfeer.filter(s => prefs.sfeer.includes(s)).length;
      return scoreB - scoreA;
    });
}
